# .github/workflows/frontend-deploy.yml
name: Frontend Deploy to Amplify

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # frontend 폴더에 변경이 있을 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Start Amplify Build
        run: |
          aws amplify start-job --app-id <YOUR_AMPLIFY_APP_ID> --branch-name main --job-type RELEASE
