name: Web Deploy (Netlify Preview)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      GMAIL_ID: ${{ secrets.GMAIL_ID }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # [수정됨] CLI 설치와 의존성 설치 단계를 하나로 통합하고 수정했습니다.
      - name: Install Dependencies & Update Netlify CLI
        run: |
          # 1. Netlify CLI를 항상 최신 버전으로 강제 업데이트합니다.
          npm install -g netlify-cli@latest
          # 2. 웹 프로젝트 폴더로 이동합니다.
          cd apps/web
          # 3. 버전 충돌을 무시하고 프로젝트 의존성을 설치합니다.
          npm install --legacy-peer-deps

      # [삭제됨] 이전의 'Install dependencies'와 'Install Netlify CLI' 단계는 위 단계로 통합되어 삭제되었습니다.

      - name: Deploy to Netlify
        run: |
          cd apps/web
          echo "=== Deploy Start ==="
          DEPLOY_OUTPUT=$(netlify deploy --build --prod \
                          --auth="$NETLIFY_AUTH_TOKEN" \
                          --site="$NETLIFY_SITE_ID" \
                          --message "GitHub Actions Production Deploy" \
                          --json)
          echo "$DEPLOY_OUTPUT"
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | jq -r '.deploy.ssl_url // .url // empty')
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
          echo "=== Deploy End ==="

      - name: Send Discord Notification
        run: |
          DEPLOY_URL="${DEPLOY_URL:-}"
          if [ -n "$DEPLOY_URL" ]; then
            MESSAGE="✅ 웹 빌드 & 배포 성공!\nPreview URL: $DEPLOY_URL"
            echo "{\"content\": \"$MESSAGE\"}" > discord_payload.json
            curl -H "Content-Type: application/json" -d @discord_payload.json "$DISCORD_WEBHOOK"
          else
            echo "빌드는 성공했지만 배포 URL이 없음 → Discord 알림 전송 안함"
          fi